# Generated by Django 5.1.3 on 2025-12-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_genero_jogo_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='genero',
            field=models.CharField(choices=[('acao', 'Ação'), ('aventura', 'Aventura'), ('rpg', 'RPG'), ('estrategia', 'Estratégia'), ('corrida', 'Corrida'), ('esportes', 'Esportes'), ('terror', 'Terror'), ('simulacao', 'Simulação'), ('luta', 'Luta'), ('tiro', 'Tiro (FPS/TPS)'), ('moba', 'MOBA'), ('plataforma', 'Plataforma')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
