# Generated by Django 5.1.3 on 2025-12-10 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0003_alter_jogo_genero_delete_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='criado_por',
        ),
    ]
