# Generated by Django 5.1.3 on 2025-12-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0005_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nota',
            field=models.IntegerField(default=5),
        ),
    ]
